services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
  
  backend:
    build: 
      context: ./backend
    container_name: backend
    restart: unless-stopped

