services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
  
  backend:
    build: 
      context: ./backend
    container_name: backend
    env_file:
      - .env
    depends_on:
      - mongodb
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: mongodb
    env_file:
      - .env
    restart: unless-stopped
    command: mongod --quiet --logpath /dev/null
